### ISSUE TITLE
Crash when converting some files into png 16bits

### ISSUE THREAD

**Issue by MaxSteven** [MrLixm/Colorspace_Converter#1]
Hello When I'm convert these files into Acescg png 16bit from Ulitity Raw then it just crash
![Leaf_Opacity_1001](https://user-images.githubusercontent.com/6467223/118352379-19f5d900-b59c-11eb-9227-09b5c7170775.jpg)

**Comment by MaxSteven** [comment]
I think I get the reason.
Because the map was exported from Substance as greyscale mode not in color mode so i think it's the reason why

**Comment by MrLixm** [comment]
Hello, Yes the app doesn’t support single-channel (aka greyscale) maps as you don’t need to apply color-transformations on scalar-greyscale maps. 

Hopes this helps.

Cheers.
Liam.
